# Generated by Django 4.1.7 on 2023-04-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_userpost_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='caption_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
