# Generated by Django 4.1.7 on 2023-04-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_networkedge'),
        ('content', '0004_alter_postmedia_media_file_postlikes_postcomments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlikes',
            unique_together={('post', 'liked_by')},
        ),
    ]
